QUICK FIX for diner api, added navigation bar to frontend (needs more…
tomatija/Menzar pull request #47
Opened 2023-02-10 11:04 UTC by tomatija

… work)

2023-02-10 11:12 UTC, tomatija commented
#46

2023-02-10 11:37 UTC, zvaktualno requested changes

2023-02-10 11:37 UTC, zvaktualno commented on backend/menzaDatabase/views.py
> +    serializerData = Diner_serializer(diners, many=True).data
Check if there are no diners.

2023-02-13 16:12 UTC, zvaktualno approved these changes

2023-02-13 16:29 UTC, merged