Review modal same day edit
tomatija/Menzar pull request #82
Opened 2023-05-01 12:04 UTC by tomatija

Fixes #53 .

2023-05-01 12:09 UTC, tomatija commented
Current fix still allows the user to open the review modal on any order and when they submit the review the server responds with an error.
Should we change this so opening the review modal is only possible on today's menu?

2023-05-04 11:26 UTC, zvaktualno requested changes

2023-05-04 11:26 UTC, zvaktualno commented on frontend/src/components/Dashboard/ReviewModal.js
> +    console.log(order);
Remove console.log

2023-05-04 11:26 UTC, zvaktualno commented on backend/menzaDatabase/views.py
> +        serializer = None
TIL: This line can be removed as Python variables don't have block scope.

2023-05-07 19:57 UTC, zvaktualno approved these changes

2023-05-07 19:57 UTC, merged